apiVersion: skaffold/v1beta12
kind: Config
build:
  # tagPolicy:
  #   gitCommit: {}
  artifacts:
  - image: yoshwata_test-file-sync
    context: .
    sync:
      manual:
      # - src: '**/foo*'
      - src: 'foo'
      #   # dest: /test
        dest: /
deploy:
 kubectl:
   manifests:
   - deployment.yaml
